# Generated by Django 4.2.8 on 2025-08-29 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireSalesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('all-season', 'All-Season'), ('summer', 'Summer'), ('winter', 'Winter'), ('performance', 'Performance'), ('off-road', 'Off-Road'), ('eco', 'Eco-Friendly'), ('run-flat', 'Run-Flat')], max_length=32)),
                ('brand', models.CharField(choices=[('michelin', 'Michelin'), ('bridgestone', 'Bridgestone'), ('goodyear', 'Goodyear'), ('continental', 'Continental'), ('pirelli', 'Pirelli'), ('other', 'Other')], max_length=32)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('tire_condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=16)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tire_sales_details', to='tracking.order')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=32)),
                ('vehicle_make', models.CharField(max_length=64)),
                ('vehicle_model', models.CharField(max_length=64)),
                ('vehicle_type', models.CharField(max_length=32)),
                ('problem_description', models.TextField(blank=True)),
                ('services_selected', models.JSONField(blank=True, default=list)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='tracking.order')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('pricing', 'Pricing'), ('services', 'Services'), ('appointment-booking', 'Appointment Booking'), ('general', 'General'), ('vehicle-purchase', 'Vehicle Purchase'), ('service-advice', 'Service Advice'), ('maintenance-plan', 'Maintenance Plan'), ('upgrade-options', 'Upgrade Options'), ('other', 'Other')], max_length=32)),
                ('questions', models.TextField()),
                ('contact_preference', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=16)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_details', to='tracking.order')),
            ],
        ),
    ]
